--------------------------------------------------------
--  File created - Selasa-Januari-06-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OKTA"."CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INVENTORY_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OKTA"."INVENTORY_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NAME_OF_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "OKTA"."NAME_OF_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 100 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OKTA_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "OKTA"."OKTA_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 100 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUPPLIER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OKTA"."SUPPLIER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "OKTA"."CUSTOMER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(8 BYTE), 
	"WEB_SITE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "OKTA"."CUSTOMERS" 
   (	"CUST_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(20 BYTE), 
	"CUST_GENDER" CHAR(1 BYTE), 
	"CUST_YEAR_OF_BIRTH" NUMBER(4,0), 
	"CUST_MARITAL_STATUS" VARCHAR2(20 BYTE), 
	"CUST_STREET_ADDRESS" VARCHAR2(40 BYTE), 
	"CUST_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"CUST_CITY" VARCHAR2(30 BYTE), 
	"CUST_CITY_ID" NUMBER, 
	"CUST_STATE_PROVINCE" VARCHAR2(40 BYTE), 
	"CUST_STATE_PROVINCE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"CUST_MAIN_PHONE_NUMBER" VARCHAR2(25 BYTE), 
	"CUST_INCOME_LEVEL" VARCHAR2(30 BYTE), 
	"CUST_CREDIT_LIMIT" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS2
--------------------------------------------------------

  CREATE TABLE "OKTA"."CUSTOMERS2" 
   (	"CUST_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(20 BYTE), 
	"CUST_LAST_NAME" VARCHAR2(20 BYTE), 
	"CUST_GENDER" CHAR(2 BYTE), 
	"CUST_YEAR_OF_BIRTH" NUMBER(4,0), 
	"CUST_MARITAL_STATUS" VARCHAR2(20 BYTE), 
	"CUST_STREET_ADDRESS" VARCHAR2(40 BYTE), 
	"CUST_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"CUST_CITY" VARCHAR2(30 BYTE), 
	"CUST_CITY_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTORY_ITEM
--------------------------------------------------------

  CREATE TABLE "OKTA"."INVENTORY_ITEM" 
   (	"ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(30 BYTE), 
	"PRICE" NUMBER(8,2), 
	"ONHAND" NUMBER, 
	"SUPPLIER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "OKTA"."SUPPLIER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"WEB_SITE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into OKTA.CUSTOMER
SET DEFINE OFF;
REM INSERTING into OKTA.CUSTOMERS
SET DEFINE OFF;
REM INSERTING into OKTA.CUSTOMERS2
SET DEFINE OFF;
REM INSERTING into OKTA.INVENTORY_ITEM
SET DEFINE OFF;
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('402','Optiplex GXPro','1500','27','302');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('403','Inspiron 7000','2500','49','302');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('404','PowerEdge 6300','7500','16','302');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('405','Inspiron 3000','2500','0','302');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('406','Inspiron 2000','2500','0','302');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('407','LaserJet 6MP','899','123','303');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('408','Jornada 2000','450','1198','303');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('409','HP 12C','69','801','303');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('410','LaserJet 2','69','3','303');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('411','Jaz PCMCIA 
adapter','125','54','303');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('412','8860 Digital 
phone','499','12','303');
Insert into OKTA.INVENTORY_ITEM (ID,DESCRIPTION,PRICE,ONHAND,SUPPLIER_ID) values ('413','Jaz carrying 
bag','20','66','303');
REM INSERTING into OKTA.SUPPLIER
SET DEFINE OFF;
Insert into OKTA.SUPPLIER (ID,NAME,WEB_SITE) values ('302','DELL','http://dell.com');
Insert into OKTA.SUPPLIER (ID,NAME,WEB_SITE) values ('303','HP','http://hp.com');
--------------------------------------------------------
--  DDL for Index INVENTORY_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OKTA"."INVENTORY_ITEM_PK" ON "OKTA"."INVENTORY_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OKTA"."CUSTOMER_PK" ON "OKTA"."CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OKTA"."CUSTOMERS2_PK" ON "OKTA"."CUSTOMERS2" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUPPLIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OKTA"."SUPPLIER_PK" ON "OKTA"."SUPPLIER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS2
--------------------------------------------------------

  ALTER TABLE "OKTA"."CUSTOMERS2" ADD CONSTRAINT "CUSTOMERS2_PK" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_YEAR_OF_BIRTH" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_STREET_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS2" MODIFY ("CUST_CITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "OKTA"."SUPPLIER" ADD CONSTRAINT "SUPPLIER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "OKTA"."SUPPLIER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."SUPPLIER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."SUPPLIER" MODIFY ("WEB_SITE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_YEAR_OF_BIRTH" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_STREET_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_CITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_STATE_PROVINCE" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_STATE_PROVINCE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMERS" MODIFY ("CUST_MAIN_PHONE_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVENTORY_ITEM
--------------------------------------------------------

  ALTER TABLE "OKTA"."INVENTORY_ITEM" ADD CONSTRAINT "INVENTORY_ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "OKTA"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "OKTA"."CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OKTA"."CUSTOMER" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY_ITEM
--------------------------------------------------------

  ALTER TABLE "OKTA"."INVENTORY_ITEM" ADD CONSTRAINT "SUPPLIED_BY" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "OKTA"."SUPPLIER" ("ID") ENABLE;
